[package]
name = "isomorph"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
num-integer = "0.1.44"
quaternion = "0.4.1"
